version: '3'
services:
  torrent-uploader:
    build: .
    container_name: torrent-uploader
    restart: unless-stopped
    ports:
      - "3300:3000"
    volumes:
      - /путь/к/вашим/торрент/папкам1:/targets/dir1
      - /путь/к/вашим/торрент/папкам2:/targets/dir2
      - /путь/к/вашим/торрент/папкам:/targets/dir3
    environment:
      - PORT=3000
